---
version: "3"
services:
  streamlit:
    image: ryosms/pixela-charts:dev
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app
    ports:
      - "8501:8501"
    command: streamlit run pixela_chart.py
    tty: yes
